### ISSUE TITLE
NullReferenceException when opening a document

### ISSUE THREAD

**Issue by rowanfreeman** [flcdrg/au-packages#113]
I just upgraded SSMS to 18.9.2.

![image](https://user-images.githubusercontent.com/445214/126922930-e4fa5225-c7ec-421a-8098-540b1663bd0d.png)

When I try to open a new file, I get a prompt asking me to select an encoding (never seen this before), and then no matter what I do that app crashes.

![image](https://user-images.githubusercontent.com/445214/126922768-5da15a29-1e79-4de9-aba4-def9517681a0.png)

If I press cancel, I get this error:

![image](https://user-images.githubusercontent.com/445214/126922834-96e37469-351e-4c75-bdbd-568263c5e993.png)

If I select Auto Detect or UTF8 or anything else and press OK, the app just closes.

I've tried restarting my PC, and uninstalling and reinstalling (with --force).

```
Application: Ssms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Text.AdornmentLibrary.Squiggles.Implementation.SquiggleVisualManager+<>c__DisplayClass17_0.<GetLines>b__0(Microsoft.VisualStudio.Text.SnapshotSpan)
   at System.Linq.Enumerable+<SelectManyIterator>d__17`2[[Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Text.Data, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.AdornmentLibrary.Squiggles.Implementation.SquiggleVisualManager.GetLines(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.SnapshotSpan>, Microsoft.VisualStudio.Text.Editor.ITextView)
   at Microsoft.VisualStudio.Text.AdornmentLibrary.Squiggles.Implementation.SquiggleVisualManager.UpdateSquigglesOnInvalidatedSpans()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by rowanfreeman** [comment]
This appears to be an issue with SSMS, because I tried installing it outside of Chocolatey and it has the same problem.

**Comment by rowanfreeman** [comment]
If anyone else runs into this problem, it's not related to this package.

For me, it turned out to be related to using Cascadia Code as my typeface.

https://github.com/microsoft/cascadia-code/issues/483
